### PR TITLE
Meter consumption data

### PR DESCRIPTION
**Pull request by arvel**
Adds a missing spec, moves reporting to its own resource and adds meter consumption data endpoint @mejackreed

### CODE REVIEW

**Comment by arvel** [comment]
@mejackreed

**Review by mejackreed — APPROVED** [review]
Thanks for the contribution!

**Comment by arvel** [comment]
@mejackreed thanks for the merge! Can you please bump the version?

**Comment by mejackreed** [comment]
@arvel v0.5.0 now released

**Pull request merged**
